[package]
name = "rbx_types"
description = "Types used to represent Roblox values"
version = "0.2.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Roblox/rbx-dom"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
blake3 = "0.1.3"
bitflags = "1.2.1"
lazy_static = "1.4.0"
rand = "0.7.3"
serde = { version = "1.0.104", features = ["derive"], optional = true }
rbx_dom_weak = { version = "1.10.1", optional = true }

[dev-dependencies]
bincode = "1.2.1"
serde_json = "1.0.45"

[features]
default = []

# Enables compatibility conversions between this crate and rbx_dom_weak v1
# types.
legacy-compat = ["rbx_dom_weak"]
