[package]
name = "rbx_binary"
description = "Implementation of Roblox's binary model (rbxm) and place (rbxl) file formats"
version = "0.6.0-dev"
license = "MIT"
documentation = "https://docs.rs/rbx_binary"
homepage = "https://github.com/rojo-rbx/rbx-dom"
repository = "https://github.com/rojo-rbx/rbx-dom.git"
readme = "README.md"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
log = "0.4.6"
lz4 = "1.23.1"
rbx_dom_weak = { path = "../rbx_dom_weak" }
rbx_reflection = { path = "../rbx_reflection" }
rbx_reflection_database = { path = "../rbx_reflection_database" }
snafu = "0.6.0"

[dev-dependencies]
base64 = "0.11.0"
criterion = "0.3"
env_logger = "0.7.1"
heck = "0.3.1"
insta = "0.16.0"
serde = { version = "1.0.103", features = ["derive"] }

[[bench]]
name = "deserializer"
harness = false

[[bench]]
name = "serializer"
harness = false
